import { useEffect, useState, type FormEvent } from 'react';
import { BrowserRouter, NavLink, Route, Routes, Navigate, useNavigate, useLocation } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { ArrowRight, ArrowUpRight, Bell, ChevronDown, CreditCard, Eye, EyeOff, Headphones, Home, LayoutGrid, LogOut, Menu, MessageCircle, Plus, Search, ShieldCheck, Wallet, FileText, CircleHelp, Check, LockKeyhole, ArrowLeftRight, Settings2, RefreshCw, X } from 'lucide-react';
import i18n, { type Locale } from './i18n';
import { api, ApiError, setCsrf } from './api';
import { Brand, Badge, Dialog, TransactionList, formatMoney, formatDate } from './components';
import { currentDestination, safeNavigation } from './navigation';
import type { User, Dashboard, AdminData, Transaction, RequestCase, Service } from './types';

import { LanguagePicker, languageLabels } from './LanguagePicker';
import { Settings } from './Settings';
import { AssistantPanel, type ChatReply } from './AssistantPanel';
import { ServiceDirectory, ServicePage, ServiceRequestDetails } from './Services';
import { serviceTitle } from './catalog';
const empty: Dashboard = { products: [], transactions: [], requests: [], audit: [] };
const navigation = [{ path: '/', label: 'home', Icon: Home }, { path: '/movements', label: 'movements', Icon: ArrowLeftRight }, { path: '/products', label: 'products', Icon: Wallet }, { path: '/services', label: 'services', Icon: LayoutGrid }, { path: '/requests', label: 'requests', Icon: FileText }];
type Modal = { type: 'transaction'; transaction: Transaction } | { type: 'request'; id: string } | { type: 'create'; transactionId?: string; service?: Service } | { type: 'handoff'; id: string } | { type: 'review'; id: string };
function errorText(error: unknown) { const key = error instanceof ApiError ? 'error.' + error.code : 'error.generic'; return i18n.t(i18n.exists(key) ? key : 'error.generic'); }

function Login({ onLogin }: { onLogin: (user: User) => void }) {
  const { t } = useTranslation(); const [identifier, setIdentifier] = useState(''); const [loginWith, setLoginWith] = useState<'email' | 'identity'>('email'); const [showPassword, setShowPassword] = useState(false); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); if (busy) return; setError(''); setBusy(true); try { const data = await api<{ user: User; csrfToken: string }>('/auth/login', 'POST', { identifier, password }); setCsrf(data.csrfToken); const chosen = i18n.language as Locale; await api('/profile/locale', 'PATCH', { locale: chosen }); onLogin({ ...data.user, locale: chosen }); setPassword(''); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }
  return <div className="login-page"><section className="login-story"><Brand light /><div className="story-content"><span className="eyebrow">NEXQORI</span><h1>{t('loginFeature')}</h1><p>{t('loginDescription')}</p><div className="story-orbit" aria-hidden="true"><span className="orbit-ring" /><span className="orbit-ring second" /><span className="orbit-logo">n.</span><span className="orbit-tile"><Wallet size={26} /></span><span className="orbit-tile second"><MessageCircle size={26} /></span></div></div><p className="story-footer">{t('tagline')}</p></section>
    <section className="login-main"><div className="login-language"><LanguagePicker onChange={locale => { void i18n.changeLanguage(locale); }} /></div><div className="login-form-wrap"><span className="round-icon"><LockKeyhole size={24} /></span><h2>{t('loginTitle')}</h2><p>{t('loginSubtitle')}</p><form onSubmit={submit} className="form-stack"><fieldset className="login-method"><legend className="sr-only">{t('loginMethod')}</legend>{(['email', 'identity'] as const).map(method => <label className={loginWith === method ? 'selected' : ''} key={method}><input type="radio" name="loginMethod" value={method} checked={loginWith === method} onChange={() => { setLoginWith(method); setIdentifier(''); setError(''); }} /><span>{t(method === 'email' ? 'emailShort' : 'identityShort')}</span></label>)}</fieldset><label>{t(loginWith === 'email' ? 'email' : 'identityNumber')}<input type={loginWith === 'email' ? 'email' : 'text'} inputMode={loginWith === 'identity' ? 'text' : 'email'} value={identifier} onChange={e => setIdentifier(e.target.value)} placeholder={t(loginWith === 'email' ? 'emailPlaceholder' : 'identityPlaceholder')} autoComplete="username" autoCapitalize="none" spellCheck={false} required maxLength={loginWith === 'email' ? 254 : 32} /></label><label>{t('password')}<span className="password-field"><input type={showPassword ? 'text' : 'password'} value={password} onChange={e => setPassword(e.target.value)} autoComplete="current-password" required maxLength={256} /><button type="button" className="icon-button" aria-label={t(showPassword ? 'hidePassword' : 'showPassword')} aria-pressed={showPassword} onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff size={18} /> : <Eye size={18} />}</button></span></label>{error && <p className="error-text" role="alert">{error}</p>}<button className="button primary wide" disabled={busy}>{busy ? t('loading') : t('signIn')}<ArrowRight size={18} /></button></form><p className="login-note"><ShieldCheck size={17} />{t('loginNote')}</p><div className="login-benefits"><span>{t('loginBenefitTitle')}</span><p>{t('loginBenefitBody')}</p></div></div></section>
  </div>;
}

function CreateRequest({ modal, data, close, saved }: { modal: Extract<Modal, { type: 'create' }>; data: Dashboard; close: () => void; saved: (id: string, duplicate: boolean) => Promise<void> }) {
  const { t, i18n } = useTranslation(); const [transactionId, setTransactionId] = useState(modal.transactionId || ''); const [reason, setReason] = useState(modal.transactionId ? 'unknown' : 'other'); const [details, setDetails] = useState(modal.service ? t('servicePrefill', { service: t(modal.service) }) : ''); const [confirmed, setConfirmed] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [requestKey] = useState(() => crypto.randomUUID());
  async function submit(e: FormEvent) { e.preventDefault(); setError(''); if (!confirmed) { setError(t('confirmationError')); return; } if (details.trim().length < 10) { setError(t('error.details')); return; } setBusy(true); try { const result = await api<{ id: string; duplicate: boolean }>('/requests', 'POST', { transactionId: transactionId || null, requestKey, service: modal.service || 'general', reason, details, confirmed }); await saved(result.id, result.duplicate); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }
  return <Dialog title={t('newRequest')} onClose={close} busy={busy}><p className="muted">{t('requestExplain')}</p><form className="form-stack" onSubmit={submit}>
    <label>{t('chooseTransaction')}<select value={transactionId} onChange={e => setTransactionId(e.target.value)}><option value="">{t('noTransaction')}</option>{data.transactions.map(tx => <option key={tx.id} value={tx.id}>{tx.merchant} · {formatMoney(tx.amountMinor, i18n.language as Locale)}</option>)}</select></label>
    <label>{t('reason')}<select value={reason} onChange={e => setReason(e.target.value)}>{['unknown', 'amount', 'payment', 'other'].map(value => <option value={value} key={value}>{t(value === 'amount' ? 'amountReason' : value)}</option>)}</select></label>
    <label>{t('detailLabel')}<textarea rows={4} value={details} onChange={e => setDetails(e.target.value)} placeholder={t('detailPlaceholder')} minLength={10} maxLength={1000} required aria-describedby="details-hint" /></label><small className="muted" id="details-hint">{t('characters')}</small>
    <label className="checkbox-label"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} />{t('confirmCheck')}</label>
    {error && <p className="error-text" role="alert">{error}</p>}<div className="dialog-actions"><button type="button" className="button secondary" disabled={busy} onClick={close}>{t('cancel')}</button><button className="button primary" disabled={busy}>{busy ? t('loading') : t('confirm')}<ArrowRight size={17} /></button></div>
  </form></Dialog>;
}

function Shell({ user, setUser, signOut }: { user: User; setUser: (user: User) => void; signOut: () => Promise<void> }) {
  const { t, i18n } = useTranslation(); const locale = i18n.language as Locale; const navigate = useNavigate(); const location = useLocation();
  const [data, setData] = useState<Dashboard>(empty); const [adminData, setAdminData] = useState<AdminData>({ users: [], requests: [], audit: [] }); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(''); const [notice, setNotice] = useState(''); const [actionError, setActionError] = useState(''); const [busy, setBusy] = useState(false);
  const [modal, setModal] = useState<Modal | null>(null); const [search, setSearch] = useState(''); const [filter, setFilter] = useState('all'); const [hidden, setHidden] = useState(false); const [menu, setMenu] = useState(false);
  async function refresh() { const next = await api<Dashboard>('/bootstrap'); setData(next); if (user.role === 'admin') setAdminData(await api<AdminData>('/admin/overview')); setLoadError(''); return next; }
  useEffect(() => { let active = true; void refresh().catch(e => { if (active) setLoadError(errorText(e)); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [user.id]);
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(''), 5500); return () => clearTimeout(timer); }, [notice]);
  useEffect(() => { setMenu(false); setActionError(''); document.querySelector('main')?.focus(); }, [location.pathname, location.search]);
  const balance = data.products.reduce((total, p) => total + (p.balanceMinor || 0), 0);
  const productFilter = new URLSearchParams(location.search).get('product');
  const productKind = new URLSearchParams(location.search).get('kind');
  const visibleProducts = data.products.filter(p => productKind === 'cards' ? p.type === 'card' : productKind === 'accounts' ? p.type !== 'card' : true);
  const visibleTransactions = data.transactions.filter(tx => (!productFilter || tx.productId === productFilter) && (filter === 'all' || tx.status === filter) && (tx.merchant + ' ' + tx.id).toLowerCase().includes(search.toLowerCase()));
  const cases = user.role === 'admin' ? adminData.requests : data.requests;
  const events = user.role === 'admin' ? adminData.audit : data.audit;
  const currentCase = modal && 'id' in modal ? cases.find(r => r.id === modal.id) : undefined;
  function open(next: Modal) { setActionError(''); setModal(next); }
  async function changeLocale(value: Locale) { try { await api('/profile/locale', 'PATCH', { locale: value }); await i18n.changeLanguage(value); setUser({ ...user, locale: value }); } catch (e) { setActionError(errorText(e)); } }
  function focusChat() { document.querySelector('.assistant-panel')?.scrollIntoView({ block: 'center', behavior: 'smooth' }); document.querySelector<HTMLInputElement>('[data-assistant-input]')?.focus({ preventScroll: true }); }
  function receiveReply(result: ChatReply) {
    if (result.destination === 'new-request') open({ type: 'create' });
    else { const route = safeNavigation(result.navigation); if (route) { navigate(route); setNotice(t('navigationDone', { screen: t(result.navigation!.destination) })); } }
  }
  useEffect(() => { document.documentElement.dataset.textSize = user.textSize || 'medium'; return () => { delete document.documentElement.dataset.textSize; }; }, [user.textSize]);
  async function confirmAction() {
    if (!modal || !('id' in modal)) return; setBusy(true); setActionError('');
    try { await api(modal.type === 'review' ? '/admin/requests/' + modal.id + '/review' : '/requests/' + modal.id + '/handoff', 'POST', { confirmed: true }); await refresh(); setNotice(t(modal.type === 'review' ? 'reviewedToast' : 'handed')); setModal({ type: 'request', id: modal.id }); } catch (e) { setActionError(errorText(e)); } finally { setBusy(false); }
  }
  function caseCard(request: RequestCase) { return <button className="case-card" key={request.id} onClick={() => open({ type: 'request', id: request.id })}><div className="case-top"><span className="case-reference">{request.id}</span><Badge status={request.status} /></div><h3>{request.catalogServiceId ? serviceTitle(request.catalogServiceId, locale) : t(request.reason === 'amount' ? 'amountReason' : request.reason)}</h3><p>{request.customerName || request.serviceData?.provider || t('requestHint')}</p><span className="text-link">{t('viewRequest')}<ArrowRight size={16} /></span></button>; }
  const pageTitle = location.pathname === '/settings' ? t('settings') : location.pathname === '/admin' ? t('admin') : t(currentDestination(location.pathname, location.search));
  function auditLabel(action: string) { return action.startsWith('navigate_') ? t('navigationRecorded', { screen: t(action.slice(9)) }) : t(action === 'handed_off' ? 'handoffEvent' : action === 'logout' ? 'logoutEvent' : action); }
  return <div className="app-shell">
    <a className="skip-link" href="#main">{t('skip')}</a>
    <aside className={'sidebar ' + (menu ? 'mobile-open' : '')}><button className="icon-button menu-close" aria-label={t('close')} onClick={() => setMenu(false)}><X size={22} /></button><NavLink className="brand-link" to={user.role === 'admin' ? '/admin' : '/'} aria-label="Nexqori"><Brand /></NavLink><p className="brand-tagline">{t('tagline')}</p><p className="nav-label">{t('workspace')}</p><nav aria-label={t('workspace')}>{(user.role === 'admin' ? [{ path: '/admin', label: 'admin', Icon: ShieldCheck }] : navigation).map(({ path, label, Icon }) => <NavLink key={path} to={path} end className={({ isActive }) => 'nav-link ' + (isActive ? 'active' : '')}><Icon size={20} /><span>{t(label)}</span>{label === 'requests' && data.requests.length > 0 && <span className="nav-count">{data.requests.length}</span>}</NavLink>)}</nav>
    <div className="sidebar-bottom"><NavLink to="/settings" className="nav-link"><Settings2 size={20} />{t('settings')}</NavLink><p className="nav-label">{t('support')}</p><NavLink to="/help" className="nav-link"><CircleHelp size={20} />{t('help')}</NavLink>{user.role === 'customer' && <button className="sidebar-help" onClick={() => { setMenu(false); focusChat(); }}><span className="round-icon small"><Headphones size={21} /></span><strong>{t('assistantHint')}</strong><span>{t('focusAssistant')} <ArrowUpRight size={15} /></span></button>}<button className="nav-link logout" onClick={() => { void signOut().catch(e => setActionError(errorText(e))); }}><LogOut size={19} />{t('logout')}</button><p className="sidebar-version">nexqori · v0.1</p></div></aside>
    {menu && <button className="menu-backdrop" aria-label={t('close')} onClick={() => setMenu(false)} />}<div className="workspace"><header className="topbar"><div className="topbar-left"><button className="icon-button menu-toggle" onClick={() => setMenu(!menu)} aria-label={t('menu')} aria-expanded={menu}><Menu size={22} /></button><span className="breadcrumb">nexqori <span>/</span> <strong>{pageTitle}</strong></span></div><div className="topbar-actions"><LanguagePicker onChange={value => { void changeLocale(value); }} />{user.role === 'customer' && <button className="icon-button" aria-label={t('notifications')} onClick={() => navigate('/requests')}><Bell size={19} /></button>}<span className="avatar" title={user.name}>{user.name.split(' ').map(n => n[0]).slice(0, 2).join('')}</span></div></header>
    <div className={'workspace-body ' + (user.role === 'admin' ? 'admin-layout' : '')}><main id="main" tabIndex={-1}>
      {actionError && !modal && <p className="error-banner" role="alert">{actionError}</p>}
      {loading ? <div className="loading-panel" role="status"><RefreshCw className="spin" />{t('loading')}</div> : loadError ? <div className="empty-panel"><p role="alert">{loadError}</p><button className="button secondary" onClick={() => { setLoading(true); void refresh().catch(e => setLoadError(errorText(e))).finally(() => setLoading(false)); }}>{t('retry')}</button></div> :
      <Routes>
        <Route path="/settings" element={<Settings user={user} setUser={setUser} />} />
        <Route path="/" element={user.role === 'admin' ? <Navigate to="/admin" replace /> : <><div className="greeting"><p className="eyebrow">{t('greeting', { name: user.name.split(' ')[0] })} <span aria-hidden="true">✳</span></p><h1>{t('welcome')}</h1><p>{t('overview')}</p></div>
          <section className="balance-card"><div className="balance-decoration" aria-hidden="true" /><div className="balance-heading"><span>{t('balance')}</span><button className="icon-button on-dark" aria-label={t(hidden ? 'showBalance' : 'hideBalance')} onClick={() => setHidden(!hidden)}>{hidden ? <EyeOff size={19} /> : <Eye size={19} />}</button></div><div className="balance-number">{hidden ? '••••••' : formatMoney(balance, locale)}</div><p>{t('accountsTotal')}</p><div className="balance-footer"><button className="button light-button" onClick={() => navigate('/movements')}>{t('seeMovements')}<ArrowUpRight size={17} /></button><span className="balance-brand" aria-hidden="true">n.</span></div></section>
          <section className="quick-section"><div className="section-heading"><div><h2>{t('shortcutTitle')}</h2><p>{t('shortcutSubtitle')}</p></div></div><div className="quick-actions">{[{ key: 'askBalance', hint: 'balanceHint', Icon: Wallet, click: () => navigate('/products') }, { key: 'report', hint: 'reportHint', Icon: Search, click: () => open({ type: 'create' }) }, { key: 'track', hint: 'trackHint', Icon: FileText, click: () => navigate('/requests') }].map(({ key, hint, Icon, click }) => <button key={key} className="quick-action" onClick={click}><span className="quick-icon"><Icon size={21} /></span><strong>{t(key)}</strong><small>{t(hint)}</small><ArrowUpRight className="quick-arrow" size={16} /></button>)}</div></section>
          <section className="panel"><div className="section-heading"><h2>{t('recent')}</h2><button className="text-link" onClick={() => navigate('/movements')}>{t('seeAll')}<ArrowRight size={16} /></button></div>{data.transactions.length ? <TransactionList compact rows={data.transactions.slice(0, 4)} onSelect={transaction => open({ type: 'transaction', transaction })} /> : <p className="empty-copy">{t('noResults')}</p>}</section>
          {data.requests.length > 0 && <section className="progress-summary"><span className="round-icon small"><FileText size={20} /></span><div><h3>{t('myRequests')}</h3><p>{data.requests[0].id} · {t(data.requests[0].status)}</p></div><button className="icon-button" aria-label={t('viewRequest')} onClick={() => open({ type: 'request', id: data.requests[0].id })}><ArrowRight size={21} /></button></section>}
        </>} />
        <Route path="/movements" element={<><PageHeading title={t('movements')} subtitle={t('activityNote')} /><div className="filters"><label className="search-field"><Search size={19} /><span className="sr-only">{t('search')}</span><input type="search" placeholder={t('search')} value={search} onChange={e => setSearch(e.target.value)} /></label><label><span className="sr-only">{t('status')}</span><select value={filter} onChange={e => setFilter(e.target.value)} aria-label={t('status')}>{['all', 'completed', 'pending', 'declined'].map(status => <option key={status} value={status}>{t(status)}</option>)}</select></label></div><section className="panel transaction-panel"><TransactionList rows={visibleTransactions} onSelect={transaction => open({ type: 'transaction', transaction })} />{!visibleTransactions.length && <div className="empty-panel"><Search size={30} /><p>{t('noResults')}</p><button className="button secondary" onClick={() => { setSearch(''); setFilter('all'); navigate('/movements'); }}>{t('clear')}</button></div>}</section></>} />
        <Route path="/products" element={<><PageHeading title={t(productKind === 'accounts' || productKind === 'cards' ? productKind : 'products')} subtitle={t('productHint')} /><div className="product-grid">{visibleProducts.map(p => <article className={'product-card product-kind-' + p.type} key={p.id}><div className="section-heading"><span className="round-icon small">{p.type === 'card' ? <CreditCard size={22} /> : <Wallet size={22} />}</span><Badge status="active" /></div><h2>{t(p.type)}</h2><p className="muted">{t('ending')} •••• {p.last4}</p><strong className="product-amount">{p.balanceMinor === null ? '•••• •••• •••• ' + p.last4 : hidden ? '••••••' : formatMoney(p.balanceMinor, locale)}</strong><button className="text-link" onClick={() => { setSearch(''); setFilter('all'); navigate('/movements?product=' + encodeURIComponent(p.id)); }}>{t('seeMovements')}<ArrowRight size={17} /></button></article>)}</div>{!visibleProducts.length && <p className="empty-panel">{t('noProducts')}</p>}</>} />
        <Route path="/services" element={<ServiceDirectory />} />
        <Route path="/services/:category" element={<ServiceDirectory />} />
        <Route path="/services/catalog/:serviceId" element={<ServicePage data={data} saved={async () => { await refresh(); }} />} />
        <Route path="/requests" element={<><PageHeading title={t('requests')} subtitle={t('requestHint')} /><button className="button primary new-request" onClick={() => open({ type: 'create' })}><Plus size={18} />{t('newRequest')}</button><div className="requests-grid">{data.requests.map(caseCard)}</div>{!data.requests.length && <div className="empty-panel"><FileText size={32} /><h2>{t('noRequests')}</h2><p>{t('createFirst')}</p></div>}</>} />
        <Route path="/help" element={<><PageHeading title={t('helpTitle')} subtitle={t('helpBody')} /><div className="help-list">{[1, 2, 3].map(n => <details key={n}><summary>{t('help' + n)}<ChevronDown size={18} /></summary><p>{t('answer' + n)}</p></details>)}</div>{user.role === 'customer' && <button className="button primary" onClick={focusChat}><MessageCircle size={19} />{t('focusAssistant')}</button>}</>} />
        <Route path="/admin" element={user.role !== 'admin' ? <Navigate to="/" replace /> : <><PageHeading title={t('adminTitle')} subtitle={t('adminNote')} /><div className="requests-grid">{adminData.requests.map(caseCard)}</div><section className="panel admin-users"><h2>{t('users')}</h2><div className="table-scroll"><table><thead><tr><th>{t('customer')}</th><th>{t('email')}</th><th>{t('status')}</th><th>{t('language')}</th></tr></thead><tbody>{adminData.users.map(u => <tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td>{t(u.role === 'admin' ? 'agent' : 'customer')}</td><td>{languageLabels[u.locale]}</td></tr>)}</tbody></table></div></section><section className="panel"><h2>{t('audit')}</h2><ul className="audit-list">{adminData.audit.slice(0, 30).map(event => <li key={event.id}><span><strong>{auditLabel(event.action)}</strong><small>{event.actorName} · {event.requestId || '—'}</small></span><time>{formatDate(event.at, locale)}</time></li>)}</ul></section></>} />
        <Route path="*" element={<Navigate to={user.role === 'admin' ? '/admin' : '/'} replace />} />
      </Routes>}
      <footer className="main-footer"><ShieldCheck size={14} />{t('footerNote')}<span>ES / EN / PT</span></footer>
    </main>
    {user.role === 'customer' && <AssistantPanel key={user.id} currentPage={currentDestination(location.pathname, location.search)} onReply={receiveReply} />}
    </div></div>
    {notice && <div className="toast" role="status"><Check size={18} />{notice}</div>}
    {modal?.type === 'create' && <CreateRequest key={modal.transactionId || modal.service || 'new'} modal={modal} data={data} close={() => setModal(null)} saved={async (id, duplicate) => { await refresh(); setNotice(t(duplicate ? 'duplicate' : 'saved')); navigate('/requests'); open({ type: 'request', id }); }} />}
    {modal?.type === 'transaction' && <Dialog title={t('movementTitle')} onClose={() => setModal(null)}><div className="transaction-detail"><h3>{modal.transaction.merchant}</h3><strong>{formatMoney(modal.transaction.amountMinor, locale)}</strong><Badge status={modal.transaction.status} /></div><dl className="detail-list"><div><dt>{t('reference')}</dt><dd>{modal.transaction.id}</dd></div><div><dt>{t('date')}</dt><dd>{formatDate(modal.transaction.date, locale)}</dd></div><div><dt>{t('product')}</dt><dd>•••• {data.products.find(p => p.id === modal.transaction.productId)?.last4}</dd></div></dl><p className="info-banner">{t(modal.transaction.status === 'pending' ? 'pendingNote' : modal.transaction.status === 'declined' ? 'declinedNote' : 'noRefund')}</p><button className="button primary wide" onClick={() => open({ type: 'create', transactionId: modal.transaction.id })}>{t('createAbout')}<ArrowRight size={17} /></button></Dialog>}
    {modal?.type === 'request' && currentCase && <Dialog title={t('requestTitle')} onClose={() => setModal(null)}><div className="case-top"><strong>{currentCase.id}</strong><Badge status={currentCase.status} /></div><h3>{currentCase.catalogServiceId ? serviceTitle(currentCase.catalogServiceId, locale) : t(currentCase.reason === 'amount' ? 'amountReason' : currentCase.reason)}</h3><ServiceRequestDetails request={currentCase} /><p className="case-details">{currentCase.catalogServiceId && currentCase.serviceData ? currentCase.serviceData.notes : currentCase.details}</p><ol className="timeline">{events.filter(event => event.requestId === currentCase.id).slice().reverse().map(event => <li key={event.id}><span className="timeline-dot"><Check size={12} /></span><div><strong>{t(event.action === 'handed_off' ? 'handoffEvent' : event.action)}</strong><p>{formatDate(event.at, locale)} · {event.actorName}</p></div></li>)}</ol>{currentCase.status === 'handed_off' && <p className="info-banner">{t('noHuman')}</p>}{user.role === 'customer' && currentCase.status !== 'handed_off' && <button className="button secondary wide" onClick={() => open({ type: 'handoff', id: currentCase.id })}><Headphones size={18} />{t('handoff')}</button>}{user.role === 'admin' && currentCase.status === 'received' && <button className="button primary wide" onClick={() => open({ type: 'review', id: currentCase.id })}>{t('startReview')}</button>}</Dialog>}
    {(modal?.type === 'handoff' || modal?.type === 'review') && <Dialog title={t(modal.type === 'review' ? 'startReview' : 'handoff')} onClose={() => setModal(null)} busy={busy}><p>{modal.type === 'handoff' ? t('handoffExplain') : currentCase?.id}</p>{actionError && <p className="error-text" role="alert">{actionError}</p>}<div className="dialog-actions"><button className="button secondary" onClick={() => setModal(null)} disabled={busy}>{t('cancel')}</button><button className="button primary" disabled={busy} onClick={() => { void confirmAction(); }}>{busy ? t('loading') : t(modal.type === 'review' ? 'startReview' : 'confirmHandoff')}</button></div></Dialog>}
  </div>;
}
function PageHeading({ title, subtitle }: { title: string; subtitle: string }) { return <div className="page-heading"><h1>{title}</h1><p>{subtitle}</p></div>; }

function Root() {
  const [user, setUser] = useState<User | null>(null); const [ready, setReady] = useState(false); const [bootError, setBootError] = useState(''); const navigate = useNavigate(); const { t } = useTranslation();
  useEffect(() => { const end = () => { setUser(null); setCsrf(''); }; window.addEventListener('nexqori-session-ended', end); void api<{ user: User; csrfToken: string }>('/session').then(result => { setCsrf(result.csrfToken); setUser(result.user); void i18n.changeLanguage(result.user.locale); }).catch(error => { if (!(error instanceof ApiError && error.status === 401)) setBootError(errorText(error)); }).finally(() => setReady(true)); return () => window.removeEventListener('nexqori-session-ended', end); }, []);
  async function signOut() { await api('/auth/logout', 'POST', {}); setCsrf(''); setUser(null); navigate('/', { replace: true }); }
  if (!ready) return <div className="loading-screen"><Brand /><p role="status">{t('loading')}</p></div>;
  if (!user) return <>{bootError && <div className="error-banner" role="alert">{bootError}</div>}<Login onLogin={next => { setUser(next); setBootError(''); navigate(next.role === 'admin' ? '/admin' : '/', { replace: true }); }} /></>;
  return <Shell user={user} setUser={setUser} signOut={signOut} />;
}
export default function App() { return <BrowserRouter><Root /></BrowserRouter>; }
