import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { api } from './api';
import { Dialog } from './components';
import type { AuditEvent, ConversationPage, User } from './types';

type Page={events:AuditEvent[];actions:string[];nextOffset:number|null};
export function AuditPanel({users,onRequest}:{users:User[];onRequest:(id:string)=>void}){
  const {t,i18n}=useTranslation();const [userId,setUserId]=useState('');const [action,setAction]=useState('');
  const [page,setPage]=useState<Page>({events:[],actions:[],nextOffset:null});const [busy,setBusy]=useState(false);const [error,setError]=useState(false);
  const [conversation,setConversation]=useState<(ConversationPage&{customerName:string})|null>(null);
  const label=(value:string)=>value.startsWith('navigate_')?t('navigationRecorded',{screen:t(value.slice(9))}):t('auditActions.'+value,{defaultValue:t(value)});
  async function load(offset=0,signal?:AbortSignal){setBusy(true);setError(false);try{const value=await api<Page>('/admin/audit?'+new URLSearchParams({userId,action,offset:String(offset)}),'GET',undefined,signal);setPage(old=>({...value,events:offset?[...old.events,...value.events]:value.events}));}catch{if(!signal?.aborted)setError(true);}finally{if(!signal?.aborted)setBusy(false);}}
  useEffect(()=>{const control=new AbortController();void load(0,control.signal);return()=>control.abort();},[userId,action]);
  async function view(id:string,before?:string){setBusy(true);setError(false);try{const value=await api<ConversationPage&{customerName:string}>('/admin/conversations/'+encodeURIComponent(id)+(before?'?before='+encodeURIComponent(before):''));setConversation(old=>({...value,messages:before&&old?[...value.messages,...old.messages]:value.messages}));}catch{setError(true);}finally{setBusy(false);}}
  return <section className="panel audit-panel"><h2>{t('audit')}</h2><p className="muted">{t('auditIntro')}</p><div className="audit-filters"><label>{t('customer')}<select value={userId} onChange={e=>setUserId(e.target.value)}><option value="">{t('auditAll')}</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>{t('auditAction')}<select value={action} onChange={e=>setAction(e.target.value)}><option value="">{t('auditAll')}</option>{page.actions.map(a=><option key={a} value={a}>{label(a)}</option>)}</select></label><button disabled={busy} className="button secondary" onClick={()=>void load()}>{t('auditRefresh')}</button></div>{error&&<p role="alert" className="error-text">{t('error.generic')}</p>}
    <div className="table-scroll"><table><thead><tr><th>{t('date')}</th><th>{t('auditActor')}</th><th>{t('customer')}</th><th>{t('auditAction')}</th><th>{t('reference')}</th></tr></thead><tbody>{page.events.map(e=><tr key={e.id}><td><time>{new Date(e.at).toLocaleString(i18n.language)}</time></td><td>{e.actorName}</td><td>{users.find(u=>u.id===e.userId)?.name||e.userId}</td><td>{label(e.action)}</td><td>{e.requestId&&<button className="text-link" onClick={()=>onRequest(e.requestId!)}>{e.requestId}</button>}{e.conversationId&&<button className="text-link" disabled={busy} onClick={()=>void view(e.conversationId!)}>{t('viewConversation')}</button>}{!e.requestId&&!e.conversationId&&'—'}</td></tr>)}</tbody></table></div>{busy&&<p role="status">{t('loading')}</p>}{page.nextOffset!==null&&<button className="button secondary" disabled={busy} onClick={()=>void load(page.nextOffset!)}>{t('loadMore')}</button>}
    {conversation&&<Dialog title={conversation.customerName+' · '+t('conversation')} busy={busy} onClose={()=>setConversation(null)}><p className="muted">{t('auditReadRecorded')}</p><h3>{conversation.conversation.title||t('previousConversation')}</h3>{conversation.before&&<button className="text-link" disabled={busy} onClick={()=>void view(conversation.conversation.id,conversation.before!)}>{t('olderMessages')}</button>}<div className="audit-conversation">{conversation.messages.map(m=><article key={m.id} className={'chat-bubble '+m.role}><strong>{t(m.role==='user'?'customer':'assistant')}</strong><time>{new Date(m.at).toLocaleString(i18n.language)}</time><p lang={m.locale}>{m.text}</p></article>)}</div></Dialog>}
  </section>;
}
