import { useEffect, useId, useRef, useState, type FormEvent } from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { FileDown } from 'lucide-react';
import { api, ApiError, downloadDocument } from './api';
import { Dialog } from './components';
import type { Dashboard, Message, DocumentMeta } from './types';
import { localeTags, type Locale } from './i18n';
import './bank-flow.css';

export function DocumentDownload({document}:{document:DocumentMeta}) {
  const {t,i18n}=useTranslation();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const locked=useRef(false);
  return <div className="chat-document" data-document-id={document.id} aria-busy={busy}><strong lang={document.locale}>{document.title}</strong><time className="muted" dateTime={document.createdAt}>{new Intl.DateTimeFormat(localeTags[i18n.language as Locale],{dateStyle:'medium',timeStyle:'short',timeZone:'America/Mexico_City'}).format(new Date(document.createdAt))}</time><button className="button secondary" disabled={busy} aria-label={t('documents.download')+' · '+document.title} onClick={async()=>{if(locked.current)return;locked.current=true;setBusy(true);setError('');try{await downloadDocument(document.id,document.filename);}catch(e){setError('error.'+(e instanceof ApiError?e.code:'generic'));}finally{locked.current=false;setBusy(false);}}}><FileDown size={17} aria-hidden="true"/>{t(busy?'loading':'documents.download')}</button>{error&&<p role="alert">{t(error)}</p>}</div>;
}

export function ChatDocuments({conversationId,data,onMessage,onClose}:{conversationId:string;data:Dashboard;onMessage:(m:Message)=>void;onClose:()=>void}) {
  const {t,i18n}=useTranslation();const navigate=useNavigate();const [kind,setKind]=useState('');const [scope,setScope]=useState('all');const [productId,setProductId]=useState('');const [requestId,setRequestId]=useState('');
  const [startDate,setStartDate]=useState('');const [endDate,setEndDate]=useState('');const [allHistory,setAllHistory]=useState(false);const [busy,setBusy]=useState(false);const locked=useRef(false);const [error,setError]=useState('');const attempt=useRef<{signature:string;key:string}|null>(null);
  const [loaded,setLoaded]=useState(false);const [missing,setMissing]=useState<string[]>([]);const [retry,setRetry]=useState(0);
  useEffect(()=>{const abort=new AbortController();setLoaded(false);setError('');
    void api<{draft:{kind?:string;scope?:string;productId?:string;requestId?:string;startDate?:string;endDate?:string;allHistory?:boolean};missing:string[]}>('/conversations/'+conversationId+'/document-context','GET',undefined,abort.signal).then(({draft,missing})=>{
      setKind(draft.kind||'');setScope(draft.scope||'all');setProductId(draft.productId||'');setRequestId(draft.requestId||'');setStartDate(draft.startDate||'');setEndDate(draft.endDate||'');setAllHistory(!!draft.allHistory);setMissing(missing);setLoaded(true);
    }).catch(e=>{if(!abort.signal.aborted)setError('error.'+(e instanceof ApiError?e.code:'generic'));});return()=>abort.abort();
  },[conversationId,retry]);
  const periodId=useId();const periodErrorId=useId();
  const days=(Date.parse(endDate)-Date.parse(startDate))/86_400_000;
  const invalidPeriod=kind==='statement'&&!allHistory&&!!startDate&&!!endDate&&(!Number.isFinite(days)||days<0||days>366);
  const caseDocument=kind==='requests_summary'||kind==='claims_summary';
  const caseRows=data.requests.filter(r=>kind==='claims_summary'?r.kind==='claim':r.kind!=='claim');
  const selectionEmpty=caseDocument?!caseRows.length:!data.products.length;
  const ready=loaded&&!!kind&&(scope==='all'||!!(caseDocument?requestId:productId))&&(kind!=='statement'||allHistory||!!startDate&&!!endDate&&!invalidPeriod);
  async function submit(e:FormEvent){e.preventDefault();if(locked.current||!ready)return;locked.current=true;setBusy(true);setError('');const body={kind,scope,locale:i18n.language,...(scope==='selected'?(caseDocument?{requestId}:{productId}):{}),...(kind==='statement'?(allHistory?{allHistory:true}:{startDate,endDate}):{})};const signature=JSON.stringify(body);if(attempt.current?.signature!==signature)attempt.current={signature,key:crypto.randomUUID()};try{const r=await api<{message:Message}>('/conversations/'+conversationId+'/documents','POST',{...body,requestKey:attempt.current.key});onMessage(r.message);onClose();if(r.message.document)navigate('/documents?document='+encodeURIComponent(r.message.document.id));}catch(e){setError('error.'+(e instanceof ApiError?e.code:'generic'));}finally{locked.current=false;setBusy(false);}}
  return <Dialog title={t('documents.prepare')} onClose={onClose} busy={busy} className="chat-documents-dialog"><form className="form-stack" onSubmit={submit} aria-busy={busy}><p>{t('documents.intro')}</p>{loaded?<p className="info-banner">{t(missing.length?'documents.contextMissing':'documents.contextReady')}</p>:error?<div role="alert"><p>{t(error)}</p><button type="button" className="button secondary" onClick={()=>setRetry(v=>v+1)}>{t('retry')}</button></div>:<p role="status">{t('loading')}</p>}<fieldset className="document-fields" disabled={!loaded||busy}><label>{t('documents.type')}<select value={kind} disabled={busy} onChange={e=>{setKind(e.target.value);setScope('all');setProductId('');setRequestId('');setError('');}}><option value="">{t('documents.chooseType')}</option>{['statement','products_summary','requests_summary','claims_summary'].map(k=><option key={k} value={k}>{t('documents.'+k)}</option>)}</select></label><label>{t('documents.scope')}<select value={scope} disabled={busy} onChange={e=>{setScope(e.target.value);setError('');}}><option value="all">{t(caseDocument?(kind==='claims_summary'?'documents.allClaims':'documents.allRequests'):'documents.allProducts')}</option><option value="selected" disabled={selectionEmpty}>{t('documents.selected')}</option></select></label>{selectionEmpty&&<p className="muted" role="status">{t('documents.noSelection')}</p>}
    {scope==='selected'&&(caseDocument?<label>{t('chatFlow.case')}<select required value={requestId} disabled={busy} onChange={e=>setRequestId(e.target.value)}><option value="">—</option>{caseRows.map(r=><option key={r.id} value={r.id}>{r.id} · {t(r.status)}</option>)}</select></label>:<label>{t('product')}<select required value={productId} disabled={busy} onChange={e=>setProductId(e.target.value)}><option value="">—</option>{data.products.map(p=><option key={p.id} value={p.id}>{t(p.type)} · •••• {p.last4}</option>)}</select></label>)}
    {kind==='statement'&&<><label className="checkbox-label"><input type="checkbox" checked={allHistory} disabled={busy} onChange={e=>{setAllHistory(e.target.checked);setError('');}}/>{t('documents.allHistory')}</label>{!allHistory&&<div className="document-dates"><label>{t('documents.from')}<input type="date" required disabled={busy} value={startDate} max={endDate||undefined} aria-invalid={invalidPeriod} aria-describedby={invalidPeriod?periodErrorId:periodId} onChange={e=>setStartDate(e.target.value)}/></label><label>{t('documents.to')}<input type="date" required disabled={busy} value={endDate} min={startDate||undefined} aria-invalid={invalidPeriod} aria-describedby={invalidPeriod?periodErrorId:periodId} onChange={e=>setEndDate(e.target.value)}/></label></div>}{invalidPeriod&&<p className="error-text" id={periodErrorId}>{t('documents.periodInvalid')}</p>}<p className="muted" id={periodId}>{t('documents.periodHint')}</p></>}
    <p className="muted">{t('documents.limit')}</p>{error&&<p className="error-text" role="alert">{t(error)}</p>}<button className="button primary" disabled={busy||!ready}><FileDown size={18} aria-hidden="true"/>{t(busy?'loading':'documents.generate')}</button></fieldset></form></Dialog>;
}
