import { useEffect, useId, useRef, useState, type FormEvent } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { ArrowRight, CheckCircle2 } from 'lucide-react';
import { api, ApiError } from './api';
import { formatMoney } from './components';
import { parseAmount } from './catalog';
import type { Dashboard } from './types';
import { localeTags, type Locale } from './i18n';
import './bank-flow.css';

type Recipient={quoteId:string;name:string;reference:string;last4:string;expiresAt:number};
type Receipt={id:string;recipientName:string;senderName:string;amountMinor:number;currency:string;accountLast4:string;recipientLast4:string;date:string;transactionId:string;note:string;direction?:string};
const failure=(e:unknown)=>'error.'+(e instanceof ApiError?e.code:'generic');

export function TransferForm({data,saved}:{data:Dashboard;saved:(id:string)=>Promise<void>}){
  const {t,i18n}=useTranslation();const locale=i18n.language as Locale;const navigate=useNavigate();const accounts=data.products.filter(p=>p.type!=='card'&&p.currency==='MXN');
  const amountErrorId=useId();const recipientHeading=useRef<HTMLHeadingElement>(null);
  const [reference,setReference]=useState('');const [recipient,setRecipient]=useState<Recipient|null>(null);const [accountId,setAccountId]=useState(accounts[0]?.id||'');
  const [amount,setAmount]=useState('');const [note,setNote]=useState('');const [review,setReview]=useState(false);const [confirmed,setConfirmed]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const locked=useRef(false);const attempt=useRef<{signature:string;key:string}|null>(null);const amountMinor=parseAmount(amount);const account=accounts.find(p=>p.id===accountId);
  const invalidAmount=!!amount&&!amountMinor;const insufficient=!!amountMinor&&!!account&&amountMinor>(account.balanceMinor||0);const ready=!!recipient&&!!account&&!!amountMinor&&!insufficient;
  useEffect(()=>{if(recipient)recipientHeading.current?.focus();},[recipient,review]);
  async function lookup(e?:FormEvent){e?.preventDefault();if(locked.current)return;locked.current=true;setBusy(true);setError('');setRecipient(null);try{setRecipient(await api<Recipient>('/transfers/recipient','POST',{reference}));}catch(e){setError(failure(e));}finally{locked.current=false;setBusy(false);}}
  async function transfer(e:FormEvent){e.preventDefault();if(!recipient||!confirmed||!ready||locked.current||error==='error.recipient_expired')return;locked.current=true;setBusy(true);setError('');const body={quoteId:recipient.quoteId,accountId,amountMinor,note,confirmed:true};const signature=JSON.stringify(body);if(attempt.current?.signature!==signature)attempt.current={signature,key:crypto.randomUUID()};try{const r=await api<Receipt>('/transfers','POST',{...body,requestKey:attempt.current.key});navigate('/transfers/'+r.id);void saved(r.id).catch(()=>{});}catch(e){setError(failure(e));}finally{locked.current=false;setBusy(false);}}
  return <div className="service-workspace"><Link className="text-link" to="/services/transfers">{t('allServices')}</Link><h1>{t('transfer.title')}</h1><p>{t('transfer.intro')}</p><section className="panel phone-bill" aria-busy={busy}>
    {!review&&<form className="form-stack" onSubmit={lookup}><label>{t('transfer.reference')}<input required inputMode="numeric" pattern="[0-9]{12,18}" minLength={12} maxLength={32} value={reference} disabled={busy} autoComplete="off" spellCheck={false} onChange={e=>{setReference(e.target.value.replace(/\s/g,''));setRecipient(null);setError('');}}/></label><button className="button primary" disabled={busy||!/^\d{12,18}$/.test(reference)}>{t(busy?'loading':'transfer.find')}</button></form>}
    {recipient&&<><div className="recipient-card"><p className="eyebrow">{t(review?'transfer.review':'transfer.recipient')}</p><h2 ref={recipientHeading} tabIndex={-1}>{recipient.name}</h2><p>•••• {recipient.last4}</p><p>{recipient.reference}</p></div>{!review?<form className="form-stack" onSubmit={e=>{e.preventDefault();if(ready){setReview(true);setConfirmed(false);setError('');}}}>
      <label>{t('catalogSourceAccount')}<select value={accountId} disabled={busy} onChange={e=>setAccountId(e.target.value)} required>{accounts.map(p=><option key={p.id} value={p.id}>{t(p.type)} · •••• {p.last4} · {formatMoney(p.balanceMinor||0,locale,p.currency)}</option>)}</select></label>{!accounts.length&&<p role="status">{t('noProducts')}</p>}<label>{t('amount')}<input inputMode="decimal" required maxLength={14} value={amount} disabled={busy} aria-invalid={invalidAmount||insufficient} aria-describedby={invalidAmount||insufficient?amountErrorId:undefined} onChange={e=>setAmount(e.target.value)}/></label>{(invalidAmount||insufficient)&&<p id={amountErrorId} className="error-text">{t(insufficient?'error.insufficient_funds':'error.service_amount')}</p>}<label>{t('transfer.note')}<input value={note} maxLength={140} disabled={busy} onChange={e=>setNote(e.target.value)}/></label><button className="button primary" disabled={!ready||busy}>{t('transfer.review')}<ArrowRight size={18}/></button>
    </form>:<form className="form-stack" onSubmit={transfer}><div className="bill-total"><span>{t('transfer.toSend')}</span><strong>{formatMoney(amountMinor||0,locale)}</strong></div><p>{t('pay.debitFrom',{account:account?.last4})}</p>{note&&<p className="transfer-note">{note}</p>}<label className="checkbox-label"><input type="checkbox" checked={confirmed} disabled={busy||error==='error.recipient_expired'} onChange={e=>setConfirmed(e.target.checked)}/>{t('transfer.confirmCheck')}</label><div className="service-form-actions"><button className="button secondary" type="button" disabled={busy} onClick={()=>setReview(false)}>{t('catalogEdit')}</button><button className="button primary" disabled={!confirmed||busy||error==='error.recipient_expired'}>{t(busy?'loading':'transfer.confirm')}</button></div></form>}</>}
    {error&&<p role="alert" className="error-text">{t(error)}</p>}{error==='error.recipient_expired'&&<button className="button secondary" disabled={busy} onClick={()=>{setReview(false);setConfirmed(false);void lookup();}}>{t('transfer.find')}</button>}
  </section></div>;
}

export function TransferReceipt({transferId,compact=false}:{transferId?:string;compact?:boolean}){
  const params=useParams();const {t,i18n}=useTranslation();const locale=i18n.language as Locale;const [receipt,setReceipt]=useState<Receipt|null>(null);const [error,setError]=useState('');const [retry,setRetry]=useState(0);
  useEffect(()=>{const c=new AbortController();setReceipt(null);setError('');void api<Receipt>('/transfers/'+encodeURIComponent(transferId||params.transferId||''),'GET',undefined,c.signal).then(setReceipt).catch(e=>{if(!c.signal.aborted)setError(failure(e));});return()=>c.abort();},[transferId,params.transferId,retry]);
  if(error)return <div role="alert"><p>{t(error)}</p><button className="button secondary" onClick={()=>setRetry(v=>v+1)}>{t('retry')}</button></div>;if(!receipt)return <p role="status">{t('loading')}</p>;
  return <section className={compact?'payment-receipt compact':'panel payment-receipt'} data-transfer-id={receipt.id}>{!compact&&<><span className="payment-check"><CheckCircle2 size={44}/></span><h1>{t(receipt.direction==='received'?'transfer.received':'transfer.done')}</h1><strong className="payment-amount">{formatMoney(receipt.amountMinor,locale,receipt.currency)}</strong></>}<dl className="detail-list"><div><dt>{t('operationId')}</dt><dd>{receipt.id}</dd></div><div><dt>{t('transfer.sender')}</dt><dd>{receipt.senderName} · •••• {receipt.accountLast4}</dd></div><div><dt>{t('transfer.recipient')}</dt><dd>{receipt.recipientName} · •••• {receipt.recipientLast4}</dd></div><div><dt>{t('date')}</dt><dd>{new Intl.DateTimeFormat(localeTags[locale],{dateStyle:'medium',timeStyle:'short',timeZone:'America/Mexico_City'}).format(new Date(receipt.date))}</dd></div><div><dt>{t('linkedMovement')}</dt><dd>{receipt.transactionId}</dd></div>{receipt.note&&<div><dt>{t('transfer.note')}</dt><dd>{receipt.note}</dd></div>}</dl>{!compact&&<div className="service-form-actions"><Link className="button primary" to="/movements">{t('seeMovements')}</Link><Link className="button secondary" to="/services/catalog/bank-transfer">{t('transfer.another')}</Link></div>}</section>;
}
