import type { Locale } from './i18n';
export type TextSize = 'small' | 'medium' | 'large';
export type Experience = { ageBand: '18_49' | '50_59' | '60_plus'; bankingExperience: 'new' | 'occasional' | 'frequent'; digitalExperience: 'new' | 'learning' | 'confident'; assistance: 'auto' | 'guided' | 'standard'; effectiveAssistance: 'guided' | 'standard' };
export type User = { id: string; email: string; name: string; role: 'customer' | 'admin'; locale: Locale; textSize: TextSize; experience: Experience | null };
export type Product = { status?: string; id: string; type: 'account' | 'savings' | 'card'; last4: string; balanceMinor: number | null; currency: string };
export type Transaction = { paymentId?: string | null; id: string; productId: string; merchant: string; category: string; amountMinor: number; currency: string; date: string; status: 'completed' | 'pending' | 'declined' };
export type Service = 'general' | 'accounts' | 'cards' | 'transfers' | 'payments' | 'loans' | 'investments' | 'insurance' | 'cash' | 'support';
export type ServiceItem = { workflow?: { id: string; version: string; steps: string[]; requiredFields: string[]; executesFinancialOperation: boolean } | null; id: string; category: Service; kind: 'bill' | 'transfer' | 'inquiry' | 'claim' | 'navigate'; icon: string; provider: string | null; referenceKind: 'phone' | 'customer' | 'receipt' | 'account' | null; target: string | null; reason: string; title: string; summary: string };
export type ServiceData = { provider: string | null; reference: string; beneficiary: string; amountMinor: number | null; currency: string | null; accountLast4: string | null; notes: string };
export type RefundSummary = { id: string; status: 'pending' | 'approved' | 'rejected'; amountMinor: number; currency: string; createdAt: string; decidedAt: string | null; creditTransactionId: string | null };
export type RequestCase = { kind?: "claim" | "application"; id: string; userId: string; transactionId: string | null; service: Service; catalogServiceId?: string | null; sourceProductId?: string | null; serviceData?: ServiceData | null; reason: 'unknown' | 'amount' | 'payment' | 'other'; details: string; status: 'received' | 'in_review' | 'handed_off'; createdAt: string; updatedAt: string; customerName?: string; refund?: RefundSummary | null };
export type AuditEvent = { transactionId?: string | null; productId?: string | null; conversationId: string | null; id: string; userId: string; requestId: string | null; action: string; actorId: string; actorName: string; at: string };
export type Message = { id: string; role: 'assistant' | 'user'; text: string; locale: Locale; at: string };
export type Conversation = { id: string; title: string | null; locale: Locale; transactionId?: string | null; createdAt: string; updatedAt: string };
export type ConversationPage = { flow?: import('./ChatFlow').FlowResult | null; conversation: Conversation; messages: Message[]; before: string | null };
export type ConversationList = { conversations: Conversation[]; nextOffset: number | null };
export type Dashboard = { products: Product[]; transactions: Transaction[]; requests: RequestCase[]; audit: AuditEvent[] };
export type AdminData = { users: User[]; requests: RequestCase[]; audit: AuditEvent[] };
