import type { Locale } from './i18n';
export type User = { id: string; email: string; name: string; role: 'customer' | 'admin'; locale: Locale };
export type Product = { id: string; type: 'account' | 'savings' | 'card'; last4: string; balanceMinor: number | null; currency: string };
export type Transaction = { id: string; productId: string; merchant: string; category: string; amountMinor: number; currency: string; date: string; status: 'completed' | 'pending' | 'declined' };
export type Service = 'general' | 'accounts' | 'cards' | 'transfers' | 'payments' | 'loans' | 'investments' | 'insurance' | 'cash' | 'support';
export type RequestCase = { id: string; userId: string; transactionId: string | null; service: Service; reason: 'unknown' | 'amount' | 'payment' | 'other'; details: string; status: 'received' | 'in_review' | 'handed_off'; createdAt: string; updatedAt: string; customerName?: string };
export type AuditEvent = { id: string; userId: string; requestId: string | null; action: string; actorId: string; actorName: string; at: string };
export type Message = { id: string; role: 'assistant' | 'user'; text: string; locale: Locale; at: string };
export type Dashboard = { products: Product[]; transactions: Transaction[]; requests: RequestCase[]; audit: AuditEvent[]; messages: Message[] };
export type ChatFeedbackMetric = { responses: number; averageScore: number | null; npsScore: number | null; csatPercent: number | null; averageFormDurationMs: number | null; averageConversationDurationMs: number | null };
export type AdminData = { users: User[]; requests: RequestCase[]; audit: AuditEvent[]; chatFeedback: { nps: ChatFeedbackMetric; csat: ChatFeedbackMetric; ces: ChatFeedbackMetric } };
